export type GameCategory = "casual" | "reels" | "table" | "skill";

export interface GameItem {
  id: string;
  name: string;
  slug: string;
  thumbnail: string;
  category: GameCategory;
  isPopular: boolean;
  isNew: boolean;
  sortOrder: number;
  enabled: boolean;
  alt: string;
}

export const games: GameItem[] = [
  {
    id: "royal-roulette",
    name: "Royal Roulette",
    slug: "/play/royal-roulette",
    thumbnail: "/images/games/royal-roulette.webp",
    category: "table",
    isPopular: true,
    isNew: true,
    sortOrder: 1,
    enabled: true,
    alt: "Original black emerald and gold royal roulette wheel with an ivory ball in motion",
  },
  {
    id: "thunder-gods",
    name: "Thunder Gods",
    slug: "/play/thunder-gods",
    thumbnail: "/images/games/thunder-gods.webp",
    category: "reels",
    isPopular: true,
    isNew: true,
    sortOrder: 2,
    enabled: true,
    alt: "Original silver-haired storm guardian charging fantasy symbols with blue lightning",
  },
  {
    id: "car-roulette",
    name: "Car Roulette",
    slug: "/play/car-roulette",
    thumbnail: "/images/games/car-roulette.webp",
    category: "casual",
    isPopular: true,
    isNew: true,
    sortOrder: 3,
    enabled: true,
    alt: "Three fictional neon performance cars racing around an elevated circular track",
  },
  {
    id: "red-vs-black",
    name: "Red vs Black",
    slug: "/play/red-vs-black",
    thumbnail: "/images/games/red-vs-black.webp",
    category: "table",
    isPopular: true,
    isNew: true,
    sortOrder: 4,
    enabled: true,
    alt: "Original crimson regent and black-armored sentinel facing off over an emerald card table",
  },
  {
    id: "sic-bo",
    name: "Sic Bo",
    slug: "/play/sic-bo",
    thumbnail: "/images/games/sic-bo.webp",
    category: "table",
    isPopular: true,
    isNew: true,
    sortOrder: 5,
    enabled: true,
    alt: "Three ivory dice tumbling inside an ornate jade and gold glass chamber",
  },
  {
    id: "flight-x",
    name: "Crash",
    slug: "/play/flight-x",
    thumbnail: "/images/games/flight-x.webp",
    category: "casual",
    isPopular: true,
    isNew: true,
    sortOrder: 6,
    enabled: true,
    alt: "Original silver and cobalt futuristic jet climbing from a sunset city toward space",
  },
  {
    id: "dragon-tiger",
    name: "Dragon Tiger",
    slug: "/play/dragon-tiger",
    thumbnail: "/images/games/dragon-tiger.webp",
    category: "table",
    isPopular: true,
    isNew: true,
    sortOrder: 7,
    enabled: true,
    alt: "Original luminous jade dragon and white-gold tiger confronting each other above a temple card table",
  },
  {
    id: "money-machine",
    name: "Money Machine",
    slug: "/play/money-machine",
    thumbnail: "/images/games/money-machine.webp",
    category: "reels",
    isPopular: true,
    isNew: true,
    sortOrder: 8,
    enabled: true,
    alt: "Original five-reel brass money machine glowing inside a vast art-deco vault",
  },
  {
    id: "777-slots",
    name: "777 Slots",
    slug: "/play/777-slots",
    thumbnail: "/images/games/777-slots.webp",
    category: "reels",
    isPopular: true,
    isNew: true,
    sortOrder: 20,
    enabled: true,
    alt: "Original red-and-gold 777 slot machine celebrating a triple-seven jackpot",
  },
  {
    id: "teen-patti",
    name: "Teen Patti",
    slug: "/play/teen-patti",
    thumbnail: "/images/games/teen-patti.webp",
    category: "table",
    isPopular: true,
    isNew: true,
    sortOrder: 21,
    enabled: true,
    alt: "Three aces and red-and-gold chips on a premium emerald card table",
  },
  {
    id: "precision-arena",
    name: "Precision Arena",
    slug: "/play/precision-arena",
    thumbnail: "/images/games/precision-arena.webp",
    category: "skill",
    isPopular: true,
    isNew: false,
    sortOrder: 10,
    enabled: true,
    alt: "Bow and arrow aimed at an archery target",
  },
  {
    id: "eight-ball",
    name: "8 Ball",
    slug: "/play/eight-ball",
    thumbnail: "/images/games/eight-ball.webp",
    category: "skill",
    isPopular: true,
    isNew: false,
    sortOrder: 20,
    enabled: true,
    alt: "Black 8-ball and cue ball on a pool table",
  },
  {
    id: "penalty-kings",
    name: "Penalty Kings",
    slug: "/play/penalty-kings",
    thumbnail: "/images/games/penalty-kings.webp",
    category: "casual",
    isPopular: true,
    isNew: true,
    sortOrder: 30,
    enabled: true,
    alt: "Football flying toward a goal as a goalkeeper dives",
  },
  {
    id: "tower-clash",
    name: "Tower Clash",
    slug: "/play/tower-clash",
    thumbnail: "/images/games/tower-clash.webp",
    category: "casual",
    isPopular: true,
    isNew: false,
    sortOrder: 40,
    enabled: true,
    alt: "Two castle towers with a cannonball flying between them",
  },
  {
    id: "neon-drift",
    name: "Neon Drift",
    slug: "/play",
    thumbnail: "/images/games/neon-drift.webp",
    category: "casual",
    isPopular: true,
    isNew: false,
    sortOrder: 50,
    enabled: true,
    alt: "Sports car drifting around a wet city road at night",
  },
];

export const orderedGames = games
  .filter((game) => game.enabled)
  .sort((a, b) => a.sortOrder - b.sortOrder);
