import { Award, Check, ChevronRight, Flame, Lock, Sparkles, Target, Zap } from "lucide-react";
import { ACHIEVEMENTS, MISSIONS } from "@/lib/neon/constants";
import { SectionHeading } from "@/components/neon/SectionHeading";

export default function MissionsPage() {
  return <div className="space-y-9 pb-10">
    <section className="relative overflow-hidden rounded-[2rem] border border-violet-300/15 bg-[radial-gradient(circle_at_85%_0%,rgba(139,92,246,.17),transparent_36%),linear-gradient(120deg,#0a0f1a,#070b12)] px-6 py-10 sm:px-10"><Target className="h-7 w-7 text-violet-300" /><p className="neon-eyebrow mt-5">Daily reset in 08:42:16</p><h1 className="font-display mt-2 text-5xl font-black italic tracking-[-.05em] text-white sm:text-7xl">KEEP THE ENGINE HOT.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-400">Race with purpose, earn XP, and turn skilled driving into permanent profile milestones.</p></section>
    <section><SectionHeading eyebrow="Today's missions" title="Three reasons to race" /><div className="grid gap-4 lg:grid-cols-3">{MISSIONS.map((mission, index) => { const complete = mission.progress >= mission.target; const percent = Math.min(100, mission.progress / mission.target * 100); return <div key={mission.id} className={`relative overflow-hidden rounded-2xl border p-5 ${complete ? "border-emerald-300/20 bg-emerald-300/[.04]" : "border-white/[.07] bg-[#090f19]"}`}><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${complete ? "bg-emerald-300 text-[#06120d]" : index === 0 ? "bg-rose-400/10 text-rose-300" : "bg-violet-400/10 text-violet-300"}`}>{complete ? <Check className="h-5 w-5" /> : index === 0 ? <Flame className="h-5 w-5" /> : <Target className="h-5 w-5" />}</span><span className="rounded-lg border border-white/[.07] px-2 py-1 text-[8px] font-black uppercase tracking-widest text-cyan-200">+{mission.reward} {mission.unit}</span></div><p className="neon-eyebrow mt-5">{mission.title}</p><h3 className="font-display mt-1 text-xl font-black italic text-white">{mission.description}</h3><div className="mt-5 flex justify-between text-[9px] font-black text-slate-500"><span>Progress</span><span className={complete ? "text-emerald-300" : "text-white"}>{mission.progress} / {mission.target}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className={`h-full rounded-full ${complete ? "bg-emerald-300" : "bg-gradient-to-r from-cyan-400 to-violet-400"}`} style={{ width: `${percent}%` }} /></div></div>})}</div></section>
    <section><SectionHeading eyebrow="Milestones" title="Achievements" copy="Permanent badges that mark the moments other drivers remember." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{ACHIEVEMENTS.map((achievement) => <div key={achievement.title} className={`group flex items-center gap-4 rounded-2xl border p-4 ${achievement.unlocked ? "border-amber-300/15 bg-amber-300/[.035]" : "border-white/[.05] bg-white/[.015] opacity-65"}`}><span className={`grid h-12 w-12 place-items-center rounded-xl border text-xl ${achievement.unlocked ? "border-amber-300/20 bg-amber-300/[.08] text-amber-200" : "border-white/[.06] text-slate-700"}`}>{achievement.unlocked ? achievement.icon : <Lock className="h-4 w-4" />}</span><div className="min-w-0 flex-1"><p className="font-display font-black italic uppercase text-white">{achievement.title}</p><p className="mt-1 text-[9px] text-slate-500">{achievement.description}</p></div>{achievement.unlocked && <Award className="h-4 w-4 text-amber-300" />}</div>)}</div></section>
    <section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#080d16] p-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.2em] text-violet-300"><Sparkles className="h-4 w-4" /> Weekly challenge</p><h3 className="font-display mt-2 text-2xl font-black italic text-white">Win 12 races in the rain</h3><p className="mt-1 text-xs text-slate-500">7 / 12 complete · Reward: animated Eclipse nitro trail</p><div className="mt-4 h-1.5 max-w-xl overflow-hidden rounded-full bg-white/[.06]"><div className="h-full w-[58%] bg-gradient-to-r from-violet-400 to-cyan-300" /></div></div><button className="flex items-center gap-2 text-[9px] font-black uppercase tracking-widest text-cyan-200">View reward <ChevronRight className="h-4 w-4" /></button></section>
    <div className="flex items-center gap-3 rounded-xl border border-cyan-300/10 bg-cyan-300/[.025] p-4 text-[9px] font-bold uppercase tracking-widest text-slate-500"><Zap className="h-4 w-4 text-cyan-300" /> Mission progress is recorded only from verified match events.</div>
  </div>;
}
