"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, Loader2, ShieldCheck } from "lucide-react";

export default function AdminLoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const response = await fetch("/api/admin/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "same-origin", body: JSON.stringify({ email, password }) }); const payload = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(payload.error || "Administrator login failed."); router.replace("/admin"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Administrator login failed."); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-md py-10"><div className="rounded-3xl border border-brand-teal/25 bg-navy-900 p-7 shadow-card"><div className="text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-teal/10 text-brand-teal"><ShieldCheck className="h-7 w-7" /></div><h1 className="mt-4 text-2xl font-black text-white">Owner administration</h1><p className="mt-1 text-xs text-slate-400">Credentials are verified only by the server. Sessions expire after eight hours.</p></div>
    <form onSubmit={submit} className="mt-6 space-y-4"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="username" placeholder="Administrator email" className="w-full rounded-xl border border-navy-700 bg-navy-950 px-4 py-3 text-sm text-white outline-none focus:border-brand-teal" /><div className="relative"><input type={show ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} required autoComplete="current-password" placeholder="Administrator password" className="w-full rounded-xl border border-navy-700 bg-navy-950 px-4 py-3 pr-11 text-sm text-white outline-none focus:border-brand-teal" /><button type="button" onClick={() => setShow((value) => !value)} aria-label={show ? "Hide password" : "Show password"} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div>{error && <p className="rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-xs text-rose-300">{error}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-brand-teal py-3.5 text-sm font-black text-navy-950 disabled:opacity-60">{busy ? <Loader2 className="h-5 w-5 animate-spin" /> : "ENTER SECURE CONSOLE"}</button></form></div></div>;
}
